# File automatically generated by autoandr 0.00.01
# "examples/apps/ncp"
#

LOCAL_PATH := $(call my-dir)

#### BEGIN ot-ncp ####
include $(CLEAR_VARS)
LOCAL_MODULE := ot-ncp
LOCAL_STATIC_LIBRARIES += libopenthread-ftd
LOCAL_STATIC_LIBRARIES += libopenthread-ncp
LOCAL_STATIC_LIBRARIES += libmbedcrypto
LOCAL_STATIC_LIBRARIES += libopenthread-posix
LOCAL_CFLAGS += -DHAVE_CONFIG_H
LOCAL_CFLAGS += -DMBEDTLS_CONFIG_FILE=\"mbedtls-config.h\"
LOCAL_CFLAGS += -Wall
LOCAL_CFLAGS += -Wextra
LOCAL_CFLAGS += -Wno-date-time
LOCAL_CFLAGS += -Wshadow
LOCAL_CFLAGS += -pedantic-errors
LOCAL_CFLAGS += -std=c99
LOCAL_CPP_FEATURES +=
LOCAL_C_INCLUDES += $(LOCAL_PATH)/.
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../examples/apps/ncp
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../examples/platforms
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../src/core
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../third_party/mbedtls
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../third_party/mbedtls/repo/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../third_party/mbedtls/repo/include/mbedtls
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../include
LOCAL_MODULE_TAGS += optional
LOCAL_SHARED_LIBRARIES += libstdc++
LOCAL_SRC_FILES += ../../../../../examples/apps/ncp/main.c
include $(BUILD_EXECUTABLE)
#### END ot-ncp ####
