# File automatically generated by autoandr 0.00.01
# "src/ncp"
#

LOCAL_PATH := $(call my-dir)

#### BEGIN libopenthread-ncp ####
include $(CLEAR_VARS)
LOCAL_MODULE := libopenthread-ncp
LOCAL_CFLAGS += -D_GNU_SOURCE
LOCAL_CFLAGS += -DHAVE_CONFIG_H
LOCAL_CFLAGS += -DMBEDTLS_CONFIG_FILE=\"mbedtls-config.h\"
LOCAL_CFLAGS += -DOPENTHREAD_TARGET_LINUX
LOCAL_CFLAGS += -pedantic-errors
LOCAL_CFLAGS += -std=c99
LOCAL_CFLAGS += -Wall
LOCAL_CFLAGS += -Wextra
LOCAL_CFLAGS += -Wno-date-time
LOCAL_CFLAGS += -Wshadow
LOCAL_C_INCLUDES += $(LOCAL_PATH)/.
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../src
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../src/core
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../src/ncp
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party/mbedtls
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party/mbedtls/repo/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party/mbedtls/repo/include/mbedtls
LOCAL_CPP_FEATURES +=
LOCAL_CPPFLAGS += -D_GNU_SOURCE
LOCAL_CPPFLAGS += -DHAVE_CONFIG_H
LOCAL_CPPFLAGS += -DMBEDTLS_CONFIG_FILE=\"mbedtls-config.h\"
LOCAL_CPPFLAGS += -DOPENTHREAD_TARGET_LINUX
LOCAL_CPPFLAGS += -std=gnu++98
LOCAL_CPPFLAGS += -Wall
LOCAL_CPPFLAGS += -Wextra
LOCAL_CPPFLAGS += -Wno-c++11-extensions
LOCAL_CPPFLAGS += -Wno-c++14-compat
LOCAL_CPPFLAGS += -Wno-date-time
LOCAL_CPPFLAGS += -Wno-gnu-anonymous-struct
LOCAL_CPPFLAGS += -Wno-nested-anon-types
LOCAL_CPPFLAGS += -Wno-non-virtual-dtor
LOCAL_CPPFLAGS += -Wno-pedantic
LOCAL_CPPFLAGS += -Wno-variadic-macros
LOCAL_CPPFLAGS += -Wno-zero-length-array
LOCAL_CPPFLAGS += -Wshadow
LOCAL_MODULE_TAGS += optional
LOCAL_SRC_FILES += ../../../../src/ncp/flen.cpp
LOCAL_SRC_FILES += ../../../../src/ncp/hdlc.cpp
LOCAL_SRC_FILES += ../../../../src/ncp/ncp_base.cpp
LOCAL_SRC_FILES += ../../../../src/ncp/ncp_buffer.cpp
LOCAL_SRC_FILES += ../../../../src/ncp/ncp_uart.cpp
LOCAL_SRC_FILES += ../../../../src/ncp/spinel.c
include $(BUILD_STATIC_LIBRARY)
#### END libopenthread-ncp ####

#### BEGIN spinel-test ####
include $(CLEAR_VARS)
LOCAL_MODULE := spinel-test
LOCAL_CFLAGS += -DHAVE_CONFIG_H
LOCAL_CFLAGS += -DMBEDTLS_CONFIG_FILE=\"mbedtls-config.h\"
LOCAL_CFLAGS += -DSPINEL_SELF_TEST=1
LOCAL_CFLAGS += -D_GNU_SOURCE
LOCAL_CFLAGS += -Wall
LOCAL_CFLAGS += -Wextra
LOCAL_CFLAGS += -Wno-date-time
LOCAL_CFLAGS += -Wshadow
LOCAL_CFLAGS += -pedantic-errors
LOCAL_CFLAGS += -std=c99
LOCAL_CPP_FEATURES +=
LOCAL_C_INCLUDES += $(LOCAL_PATH)/.
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../src/ncp
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party/mbedtls
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party/mbedtls/repo/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party/mbedtls/repo/include/mbedtls
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../include
LOCAL_MODULE_TAGS += optional
LOCAL_SRC_FILES += ../../../../src/ncp/spinel.c
include $(BUILD_EXECUTABLE)
#### END spinel-test ####
