CC26xx Driver Library: Chip Info
Chip Info
System Control
Functions
ProtocolBitVector_t ChipInfo_GetSupportedProtocol_BV (void)
Returns bit vector showing supported protocols.
static bool ChipInfo_SupportsBLE (void)
Returns true if the chip supports the BLE protocol.
static bool ChipInfo_SupportsIEEE_802_15_4 (void)
Returns true if the chip supports the IEEE 802.15.4 protocol.
static bool ChipInfo_SupportsPROPRIETARY (void)
Returns true if the chip supports propriatary protocols.
PackageType_t ChipInfo_GetPackageType (void)
Returns package type.
static bool ChipInfo_PackageTypeIs4x4 (void)
Returns true if this is a 4x4mm chip.
static bool ChipInfo_PackageTypeIs5x5 (void)
Returns true if this is a 5x5mm chip.
static bool ChipInfo_PackageTypeIs7x7 (void)
Returns true if this is a 7x7mm chip.
static bool ChipInfo_PackageTypeIsWAFER (void)
Returns true if this is a wafer sale chip (naked die).
static bool ChipInfo_PackageTypeIsWCSP (void)
Returns true if this is a WCSP chip (flip chip).
static uint32_t ChipInfo_GetDeviceIdHwRevCode (void)
Returns the internal chip HW revision code.
static uint32_t ChipInfo_GetMinorHwRev (void)
Returns minor hardware revision number.
static uint32_t ChipInfo_GetUserId (void)
Returns the 32 bits USER_ID field.
ChipType_t ChipInfo_GetChipType (void)
Returns chip type.
ChipFamily_t ChipInfo_GetChipFamily (void)
Returns chip family member.
static bool ChipInfo_ChipFamilyIsCC26xx (void)
Returns true if this chip is member of the CC26xx family.
static bool ChipInfo_ChipFamilyIsCC13xx (void)
Returns true if this chip is member of the CC13xx family.
static bool ChipInfo_ChipFamilyIsCC26xx_R2 (void)
Returns true if this chip is member of the CC26xx_R2 family.
static bool ChipInfo_ChipFamilyIsCC26xx_Liz (void)
Returns true if this chip is member of the CC26xx_Liz family.
static bool ChipInfo_ChipFamilyIsCC26xx_Aga (void)
Returns true if this chip is member of the CC26xx_Aga family.
HwRevision_t ChipInfo_GetHwRevision (void)
Returns chip HW revision.
static bool ChipInfo_HwRevisionIs_1_0 (void)
Returns true if HW revision for this chip is 1.0.
static bool ChipInfo_HwRevisionIs_2_0 (void)
Returns true if HW revision for this chip is 2.0.
static bool ChipInfo_HwRevisionIs_GTEQ_2_0 (void)
Returns true if HW revision for this chip is 2.0 or greater.
static bool ChipInfo_HwRevisionIs_2_1 (void)
Returns true if HW revision for this chip is 2.1.
static bool ChipInfo_HwRevisionIs_GTEQ_2_1 (void)
Returns true if HW revision for this chip is 2.1 or greater.
static bool ChipInfo_HwRevisionIs_2_2 (void)
Returns true if HW revision for this chip is 2.2.
static bool ChipInfo_HwRevisionIs_GTEQ_2_2 (void)
Returns true if HW revision for this chip is 2.2 or greater.
static bool ChipInfo_HwRevisionIs_GTEQ_2_3 (void)
Returns true if HW revision for this chip is 2.3 or greater.
void ThisCodeIsBuiltForCC26xxHwRev22AndLater_HaltIfViolated (void)
Verifies that current chip is built for CC26xx HwRev 2.2 or later and never returns if violated.
Enumerations
enum ProtocolBitVector_t { PROTOCOL_Unknown = 0, PROTOCOLBIT_BLE = 0x02, PROTOCOLBIT_IEEE_802_15_4 = 0x04, PROTOCOLBIT_Proprietary = 0x08 }
Enumeration identifying the protocols supported.
enum PackageType_t {
PACKAGE_Unknown = -1, PACKAGE_4x4 = 0, PACKAGE_5x5 = 1, PACKAGE_7x7 = 2,
PACKAGE_WAFER = 3, PACKAGE_WCSP = 4
}
Package type enumeration.
enum ChipType_t {
CHIP_TYPE_Unknown = -1, CHIP_TYPE_CC1310 = 0, CHIP_TYPE_CC1350 = 1, CHIP_TYPE_CC2620 = 2,
CHIP_TYPE_CC2630 = 3, CHIP_TYPE_CC2640 = 4, CHIP_TYPE_CC2650 = 5, CHIP_TYPE_CUSTOM_0 = 6,
CHIP_TYPE_CUSTOM_1 = 7
}
Chip type enumeration.
enum ChipFamily_t {
FAMILY_Unknown = -1, FAMILY_CC26xx = 0, FAMILY_CC13xx = 1, FAMILY_CC26xx_Liz = 2,
FAMILY_CC26xx_Aga = 3, FAMILY_CC26xx_R2 = 4
}
Chip family enumeration.
enum HwRevision_t {
HWREV_Unknown = -1, HWREV_1_0 = 10, HWREV_2_0 = 20, HWREV_2_1 = 21,
HWREV_2_2 = 22, HWREV_2_3 = 23
}
HW revision enumeration.
Detailed Description
Function Documentation
static bool ChipInfo_ChipFamilyIsCC13xx (void) inline static
Returns true if this chip is member of the CC13xx family.
Returns
Returns true if this chip is member of the CC13xx family, false otherwise.
Definition at line 387 of file chipinfo.h.
static bool ChipInfo_ChipFamilyIsCC26xx (void) inline static
Returns true if this chip is member of the CC26xx family.
Returns
Returns true if this chip is member of the CC26xx family, false otherwise.
Definition at line 373 of file chipinfo.h.
Referenced by ThisCodeIsBuiltForCC26xxHwRev22AndLater_HaltIfViolated().
static bool ChipInfo_ChipFamilyIsCC26xx_Aga (void) inline static
Returns true if this chip is member of the CC26xx_Aga family.
Returns
Returns true if this chip is member of the CC26xx_Aga family, false otherwise.
Definition at line 429 of file chipinfo.h.
static bool ChipInfo_ChipFamilyIsCC26xx_Liz (void) inline static
Returns true if this chip is member of the CC26xx_Liz family.
Returns
Returns true if this chip is member of the CC26xx_Liz family, false otherwise.
Definition at line 415 of file chipinfo.h.
static bool ChipInfo_ChipFamilyIsCC26xx_R2 (void) inline static
Returns true if this chip is member of the CC26xx_R2 family.
Returns
Returns true if this chip is member of the CC26xx_R2 family, false otherwise.
Definition at line 401 of file chipinfo.h.
ChipFamily_t ChipInfo_GetChipFamily (void)
Returns chip family member.
Returns
Returns ChipFamily_t
Definition at line 102 of file chipinfo.c.
Referenced by ChipInfo_ChipFamilyIsCC13xx(), ChipInfo_ChipFamilyIsCC26xx(), ChipInfo_ChipFamilyIsCC26xx_Aga(), ChipInfo_ChipFamilyIsCC26xx_Liz(), ChipInfo_ChipFamilyIsCC26xx_R2(), ChipInfo_GetChipType(), and ChipInfo_GetHwRevision().
ChipType_t ChipInfo_GetChipType (void)
Returns chip type.
Returns
Returns ChipType_t
Definition at line 131 of file chipinfo.c.
static uint32_t ChipInfo_GetDeviceIdHwRevCode (void) inline static
Returns the internal chip HW revision code.
Returns
Returns the internal chip HW revision code (in range 0-15)
Definition at line 263 of file chipinfo.h.
Referenced by ChipInfo_GetChipFamily(), and ChipInfo_GetHwRevision().
HwRevision_t ChipInfo_GetHwRevision (void)
Returns chip HW revision.
Returns
Returns HwRevision_t
Definition at line 178 of file chipinfo.c.
Referenced by ChipInfo_HwRevisionIs_1_0(), ChipInfo_HwRevisionIs_2_0(), ChipInfo_HwRevisionIs_2_1(), ChipInfo_HwRevisionIs_2_2(), ChipInfo_HwRevisionIs_GTEQ_2_0(), ChipInfo_HwRevisionIs_GTEQ_2_1(), ChipInfo_HwRevisionIs_GTEQ_2_2(), and ChipInfo_HwRevisionIs_GTEQ_2_3().
static uint32_t ChipInfo_GetMinorHwRev (void) inline static
Returns minor hardware revision number.
The minor revision number is set to 0 for the first market released chip and thereafter incremented by 1 for each minor hardware change.
Returns
Returns the minor hardware revision number (in range 0-127)
Definition at line 281 of file chipinfo.h.
Referenced by ChipInfo_GetHwRevision().
PackageType_t ChipInfo_GetPackageType (void)
Returns package type.
Returns
Returns PackageType_t
Definition at line 80 of file chipinfo.c.
Referenced by ChipInfo_PackageTypeIs4x4(), ChipInfo_PackageTypeIs5x5(), ChipInfo_PackageTypeIs7x7(), ChipInfo_PackageTypeIsWAFER(), and ChipInfo_PackageTypeIsWCSP().
ProtocolBitVector_t ChipInfo_GetSupportedProtocol_BV (void)
Returns bit vector showing supported protocols.
Returns
Returns ProtocolBitVector_t which is a bit vector indicating supported protocols.
Definition at line 68 of file chipinfo.c.
Referenced by ChipInfo_SupportsBLE(), ChipInfo_SupportsIEEE_802_15_4(), and ChipInfo_SupportsPROPRIETARY().
static uint32_t ChipInfo_GetUserId (void) inline static
Returns the 32 bits USER_ID field.
How to decode the USER_ID filed is described in the Technical Reference Manual (TRM)
Returns
Returns the the 32 bits USER_ID field
Definition at line 306 of file chipinfo.h.
Referenced by ChipInfo_GetChipType().
static bool ChipInfo_HwRevisionIs_1_0 (void) inline static
Returns true if HW revision for this chip is 1.0.
Returns
Returns true if HW revision for this chip is 1.0, false otherwise.
Definition at line 468 of file chipinfo.h.
static bool ChipInfo_HwRevisionIs_2_0 (void) inline static
Returns true if HW revision for this chip is 2.0.
Returns
Returns true if HW revision for this chip is 2.0, false otherwise.
Definition at line 482 of file chipinfo.h.
static bool ChipInfo_HwRevisionIs_2_1 (void) inline static
Returns true if HW revision for this chip is 2.1.
Returns
Returns true if HW revision for this chip is 2.1, false otherwise.
Definition at line 510 of file chipinfo.h.
static bool ChipInfo_HwRevisionIs_2_2 (void) inline static
Returns true if HW revision for this chip is 2.2.
Returns
Returns true if HW revision for this chip is 2.2, false otherwise.
Definition at line 538 of file chipinfo.h.
static bool ChipInfo_HwRevisionIs_GTEQ_2_0 (void) inline static
Returns true if HW revision for this chip is 2.0 or greater.
Returns
Returns true if HW revision for this chip is 2.0 or greater, false otherwise.
Definition at line 496 of file chipinfo.h.
static bool ChipInfo_HwRevisionIs_GTEQ_2_1 (void) inline static
Returns true if HW revision for this chip is 2.1 or greater.
Returns
Returns true if HW revision for this chip is 2.1 or greater, false otherwise.
Definition at line 524 of file chipinfo.h.
static bool ChipInfo_HwRevisionIs_GTEQ_2_2 (void) inline static
Returns true if HW revision for this chip is 2.2 or greater.
Returns
Returns true if HW revision for this chip is 2.2 or greater, false otherwise.
Definition at line 552 of file chipinfo.h.
Referenced by ThisCodeIsBuiltForCC26xxHwRev22AndLater_HaltIfViolated().
static bool ChipInfo_HwRevisionIs_GTEQ_2_3 (void) inline static
Returns true if HW revision for this chip is 2.3 or greater.
Returns
Returns true if HW revision for this chip is 2.3 or greater, false otherwise.
Definition at line 566 of file chipinfo.h.
static bool ChipInfo_PackageTypeIs4x4 (void) inline static
Returns true if this is a 4x4mm chip.
Returns
Returns true if this is a 4x4mm chip, false otherwise.
Definition at line 193 of file chipinfo.h.
static bool ChipInfo_PackageTypeIs5x5 (void) inline static
Returns true if this is a 5x5mm chip.
Returns
Returns true if this is a 5x5mm chip, false otherwise.
Definition at line 207 of file chipinfo.h.
static bool ChipInfo_PackageTypeIs7x7 (void) inline static
Returns true if this is a 7x7mm chip.
Returns
Returns true if this is a 7x7mm chip, false otherwise.
Definition at line 221 of file chipinfo.h.
static bool ChipInfo_PackageTypeIsWAFER (void) inline static
Returns true if this is a wafer sale chip (naked die).
Returns
Returns true if this is a wafer sale chip, false otherwise.
Definition at line 235 of file chipinfo.h.
static bool ChipInfo_PackageTypeIsWCSP (void) inline static
Returns true if this is a WCSP chip (flip chip).
Returns
Returns true if this is a WCSP chip, false otherwise.
Definition at line 249 of file chipinfo.h.
static bool ChipInfo_SupportsBLE (void) inline static
Returns true if the chip supports the BLE protocol.
Returns
Returns true if supporting the BLE protocol, false otherwise.
Definition at line 126 of file chipinfo.h.
static bool ChipInfo_SupportsIEEE_802_15_4 (void) inline static
Returns true if the chip supports the IEEE 802.15.4 protocol.
Returns
Returns true if supporting the IEEE 802.15.4 protocol, false otherwise.
Definition at line 140 of file chipinfo.h.
static bool ChipInfo_SupportsPROPRIETARY (void) inline static
Returns true if the chip supports propriatary protocols.
Returns
Returns true if supporting propriatary protocols, false otherwise.
Definition at line 154 of file chipinfo.h.
void ThisCodeIsBuiltForCC26xxHwRev22AndLater_HaltIfViolated (void)
Verifies that current chip is built for CC26xx HwRev 2.2 or later and never returns if violated.
Returns
None
Definition at line 236 of file chipinfo.c.
Referenced by SetupTrimDevice().
Enumeration Type Documentation
enum ChipFamily_t
Chip family enumeration.
Enumerator
FAMILY_Unknown
-1 means that the chip's family member is unknown.
FAMILY_CC26xx
0 means that the chip is a CC26x0 family member.
FAMILY_CC13xx
1 means that the chip is a CC13x0 family member.
FAMILY_CC26xx_Liz
2 means that the chip is a CC26x1 family member.
FAMILY_CC26xx_Aga
3 means that the chip is a CCxxx2/xxx4 family member.
FAMILY_CC26xx_R2
4 means that the chip is a CC26x0_R2 family (new ROM contents).
Definition at line 345 of file chipinfo.h.
enum ChipType_t
Chip type enumeration.
Enumerator
CHIP_TYPE_Unknown
-1 means that the chip type is unknown.
CHIP_TYPE_CC1310
0 means that this is a CC1310 chip.
CHIP_TYPE_CC1350
1 means that this is a CC1350 chip.
CHIP_TYPE_CC2620
2 means that this is a CC2620 chip.
CHIP_TYPE_CC2630
3 means that this is a CC2630 chip.
CHIP_TYPE_CC2640
4 means that this is a CC2640 chip.
CHIP_TYPE_CC2650
5 means that this is a CC2650 chip.
CHIP_TYPE_CUSTOM_0
6 means that this is a CUSTOM_0 chip.
CHIP_TYPE_CUSTOM_1
7 means that this is a CUSTOM_1 chip.
Definition at line 317 of file chipinfo.h.
enum HwRevision_t
HW revision enumeration.
Enumerator
HWREV_Unknown
-1 means that the chip's HW revision is unknown.
HWREV_1_0
10 means that the chip's HW revision is 1.0
HWREV_2_0
20 means that the chip's HW revision is 2.0
HWREV_2_1
21 means that the chip's HW revision is 2.1
HWREV_2_2
22 means that the chip's HW revision is 2.2
HWREV_2_3
23 means that the chip's HW revision is 2.3
Definition at line 440 of file chipinfo.h.
enum PackageType_t
Package type enumeration.
Enumerator
PACKAGE_Unknown
-1 means that current chip type is unknown.
PACKAGE_4x4
0 means that this is a 4x4mm chip.
PACKAGE_5x5
1 means that this is a 5x5mm chip.
PACKAGE_7x7
2 means that this is a 7x7mm chip.
PACKAGE_WAFER
3 means that this is a wafer sale chip (naked die).
PACKAGE_WCSP
4 means that this is a WCSP chip (flip chip).
Definition at line 165 of file chipinfo.h.
enum ProtocolBitVector_t
Enumeration identifying the protocols supported.
Note
This is a bit vector enumeration that indicates supported protocols. E.g: 0x06 means that the chip supports both BLE and IEEE 802.15.4
Enumerator
PROTOCOL_Unknown
None of the known protocols are supported.
PROTOCOLBIT_BLE
Bit[1] set, indicates that Bluetooth Low Energy is supported.
PROTOCOLBIT_IEEE_802_15_4
Bit[2] set, indicates that IEEE 802.15.4 is supported.
PROTOCOLBIT_Proprietary
Bit[3] set, indicates that proprietary protocols are supported.
Definition at line 99 of file chipinfo.h.