coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 85%
        threshold: 0%

ignore:
  - "tests/*"
  - "third_party/**/*"

comment:
  layout: "diff, flags, files"
  after_n_builds: 16
