coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch: off

ignore:
  - "tests/*"
  - "third_party/**/*"

comment:
  layout: "diff, flags, files"
  after_n_builds: 16
