var annotated =
[
    [ "Thread", null, [
      [ "Cli", "dd/d1d/namespaceThread_1_1Cli.html", "dd/d1d/namespaceThread_1_1Cli" ],
      [ "Coap", "d6/ddc/namespaceThread_1_1Coap.html", "d6/ddc/namespaceThread_1_1Coap" ],
      [ "Crypto", null, [
        [ "AesCcm", "d2/dde/classThread_1_1Crypto_1_1AesCcm.html", "d2/dde/classThread_1_1Crypto_1_1AesCcm" ],
        [ "Hash", "d7/d13/classThread_1_1Crypto_1_1Hash.html", "d7/d13/classThread_1_1Crypto_1_1Hash" ],
        [ "Hmac", "d3/de7/classThread_1_1Crypto_1_1Hmac.html", "d3/de7/classThread_1_1Crypto_1_1Hmac" ]
      ] ],
      [ "Ip6", "d2/de1/namespaceThread_1_1Ip6.html", "d2/de1/namespaceThread_1_1Ip6" ],
      [ "Lowpan", "df/d62/namespaceThread_1_1Lowpan.html", "df/d62/namespaceThread_1_1Lowpan" ],
      [ "Mac", null, [
        [ "ActiveScanResult", "d2/d21/structThread_1_1Mac_1_1ActiveScanResult.html", "d2/d21/structThread_1_1Mac_1_1ActiveScanResult" ],
        [ "Address", "dd/dcd/structThread_1_1Mac_1_1Address.html", "dd/dcd/structThread_1_1Mac_1_1Address" ],
        [ "ExtAddress", "d9/d3c/classThread_1_1Mac_1_1ExtAddress.html", "d9/d3c/classThread_1_1Mac_1_1ExtAddress" ],
        [ "Frame", "d5/d19/classThread_1_1Mac_1_1Frame.html", "d5/d19/classThread_1_1Mac_1_1Frame" ],
        [ "Mac", "d6/d88/classThread_1_1Mac_1_1Mac.html", "d6/d88/classThread_1_1Mac_1_1Mac" ],
        [ "Receiver", "db/d89/classThread_1_1Mac_1_1Receiver.html", "db/d89/classThread_1_1Mac_1_1Receiver" ],
        [ "Sender", "d1/d40/classThread_1_1Mac_1_1Sender.html", "d1/d40/classThread_1_1Mac_1_1Sender" ],
        [ "Whitelist", "d7/d98/classThread_1_1Mac_1_1Whitelist.html", "d7/d98/classThread_1_1Mac_1_1Whitelist" ]
      ] ],
      [ "Mle", "d2/dd4/namespaceThread_1_1Mle.html", "d2/dd4/namespaceThread_1_1Mle" ],
      [ "NetworkData", "d2/d3b/namespaceThread_1_1NetworkData.html", "d2/d3b/namespaceThread_1_1NetworkData" ],
      [ "AddressResolver", "d4/dcf/classThread_1_1AddressResolver.html", "d4/dcf/classThread_1_1AddressResolver" ],
      [ "Buffer", "db/d50/classThread_1_1Buffer.html", "db/d50/classThread_1_1Buffer" ],
      [ "BufferHeader", "d2/d60/structThread_1_1BufferHeader.html", "d2/d60/structThread_1_1BufferHeader" ],
      [ "Child", "d3/de7/classThread_1_1Child.html", "d3/de7/classThread_1_1Child" ],
      [ "KeyManager", "d6/d44/classThread_1_1KeyManager.html", "d6/d44/classThread_1_1KeyManager" ],
      [ "MeshForwarder", "dd/d1d/classThread_1_1MeshForwarder.html", "dd/d1d/classThread_1_1MeshForwarder" ],
      [ "Message", "dc/d3c/classThread_1_1Message.html", "dc/d3c/classThread_1_1Message" ],
      [ "MessageInfo", "de/dcc/structThread_1_1MessageInfo.html", "de/dcc/structThread_1_1MessageInfo" ],
      [ "MessageList", "da/d60/structThread_1_1MessageList.html", "da/d60/structThread_1_1MessageList" ],
      [ "MessageListEntry", "d9/dd7/structThread_1_1MessageListEntry.html", "d9/dd7/structThread_1_1MessageListEntry" ],
      [ "MessageQueue", "da/d1a/classThread_1_1MessageQueue.html", "da/d1a/classThread_1_1MessageQueue" ],
      [ "Neighbor", "da/dd9/classThread_1_1Neighbor.html", "da/dd9/classThread_1_1Neighbor" ],
      [ "Router", "db/d81/classThread_1_1Router.html", "db/d81/classThread_1_1Router" ],
      [ "Tasklet", "d4/d92/classThread_1_1Tasklet.html", "d4/d92/classThread_1_1Tasklet" ],
      [ "TaskletScheduler", "d8/de8/classThread_1_1TaskletScheduler.html", "d8/de8/classThread_1_1TaskletScheduler" ],
      [ "ThreadExtMacAddressTlv", "dc/d31/classThread_1_1ThreadExtMacAddressTlv.html", "dc/d31/classThread_1_1ThreadExtMacAddressTlv" ],
      [ "ThreadLastTransactionTimeTlv", "dc/dc8/classThread_1_1ThreadLastTransactionTimeTlv.html", "dc/dc8/classThread_1_1ThreadLastTransactionTimeTlv" ],
      [ "ThreadMeshLocalEidTlv", "df/d0c/classThread_1_1ThreadMeshLocalEidTlv.html", "df/d0c/classThread_1_1ThreadMeshLocalEidTlv" ],
      [ "ThreadMessageInfo", "df/d49/structThread_1_1ThreadMessageInfo.html", "df/d49/structThread_1_1ThreadMessageInfo" ],
      [ "ThreadNetif", "d3/d8e/classThread_1_1ThreadNetif.html", "d3/d8e/classThread_1_1ThreadNetif" ],
      [ "ThreadRloc16Tlv", "db/d2d/classThread_1_1ThreadRloc16Tlv.html", "db/d2d/classThread_1_1ThreadRloc16Tlv" ],
      [ "ThreadRouterMaskTlv", "dd/dd2/classThread_1_1ThreadRouterMaskTlv.html", "dd/dd2/classThread_1_1ThreadRouterMaskTlv" ],
      [ "ThreadStatusTlv", "d4/df4/classThread_1_1ThreadStatusTlv.html", "d4/df4/classThread_1_1ThreadStatusTlv" ],
      [ "ThreadTargetTlv", "df/d0b/classThread_1_1ThreadTargetTlv.html", "df/d0b/classThread_1_1ThreadTargetTlv" ],
      [ "ThreadTlv", "dd/d2b/classThread_1_1ThreadTlv.html", "dd/d2b/classThread_1_1ThreadTlv" ],
      [ "Timer", "d1/d40/classThread_1_1Timer.html", "d1/d40/classThread_1_1Timer" ],
      [ "TimerScheduler", "df/d1f/classThread_1_1TimerScheduler.html", "df/d1f/classThread_1_1TimerScheduler" ]
    ] ],
    [ "otBorderRouterConfig", "dd/dd0/structotBorderRouterConfig.html", "dd/dd0/structotBorderRouterConfig" ],
    [ "otExternalRouteConfig", "d4/d5d/structotExternalRouteConfig.html", "d4/d5d/structotExternalRouteConfig" ],
    [ "otIp6Address", "d6/d55/structotIp6Address.html", "d6/d55/structotIp6Address" ],
    [ "otIp6Prefix", "d2/ddd/structotIp6Prefix.html", "d2/ddd/structotIp6Prefix" ],
    [ "otLinkModeConfig", "d6/df6/structotLinkModeConfig.html", "d6/df6/structotLinkModeConfig" ],
    [ "otMessageInfo", "dd/d76/structotMessageInfo.html", "dd/d76/structotMessageInfo" ],
    [ "otNetifAddress", "d8/d1d/structotNetifAddress.html", "d8/d1d/structotNetifAddress" ],
    [ "otSockAddr", "d3/d28/structotSockAddr.html", "d3/d28/structotSockAddr" ],
    [ "otUdpSocket", "da/dfd/structotUdpSocket.html", "da/dfd/structotUdpSocket" ],
    [ "RadioPacket", "db/ddc/structRadioPacket.html", "db/ddc/structRadioPacket" ]
];