var annotated_dup =
[
    [ "Thread", null, [
      [ "Cli", "dd/d1d/namespaceThread_1_1Cli.html", "dd/d1d/namespaceThread_1_1Cli" ],
      [ "Coap", "d6/ddc/namespaceThread_1_1Coap.html", "d6/ddc/namespaceThread_1_1Coap" ],
      [ "Crypto", null, [
        [ "AesCcm", "d2/dde/classThread_1_1Crypto_1_1AesCcm.html", "d2/dde/classThread_1_1Crypto_1_1AesCcm" ]
      ] ],
      [ "Flen", "db/d33/namespaceThread_1_1Flen.html", "db/d33/namespaceThread_1_1Flen" ],
      [ "Hdlc", "d5/d0a/namespaceThread_1_1Hdlc.html", "d5/d0a/namespaceThread_1_1Hdlc" ],
      [ "Ip6", "d2/de1/namespaceThread_1_1Ip6.html", "d2/de1/namespaceThread_1_1Ip6" ],
      [ "Lowpan", "df/d62/namespaceThread_1_1Lowpan.html", "df/d62/namespaceThread_1_1Lowpan" ],
      [ "Mac", null, [
        [ "Address", "dd/dcd/structThread_1_1Mac_1_1Address.html", "dd/dcd/structThread_1_1Mac_1_1Address" ],
        [ "Beacon", "dc/dbd/classThread_1_1Mac_1_1Beacon.html", "dc/dbd/classThread_1_1Mac_1_1Beacon" ],
        [ "ExtAddress", "d9/d3c/classThread_1_1Mac_1_1ExtAddress.html", "d9/d3c/classThread_1_1Mac_1_1ExtAddress" ],
        [ "Frame", "d5/d19/classThread_1_1Mac_1_1Frame.html", "d5/d19/classThread_1_1Mac_1_1Frame" ],
        [ "Mac", "d6/d88/classThread_1_1Mac_1_1Mac.html", "d6/d88/classThread_1_1Mac_1_1Mac" ],
        [ "Receiver", "db/d89/classThread_1_1Mac_1_1Receiver.html", "db/d89/classThread_1_1Mac_1_1Receiver" ],
        [ "Sender", "d1/d40/classThread_1_1Mac_1_1Sender.html", "d1/d40/classThread_1_1Mac_1_1Sender" ],
        [ "Whitelist", "d7/d98/classThread_1_1Mac_1_1Whitelist.html", "d7/d98/classThread_1_1Mac_1_1Whitelist" ]
      ] ],
      [ "Mle", "d2/dd4/namespaceThread_1_1Mle.html", "d2/dd4/namespaceThread_1_1Mle" ],
      [ "NetworkData", "d2/d3b/namespaceThread_1_1NetworkData.html", "d2/d3b/namespaceThread_1_1NetworkData" ],
      [ "AddressResolver", "d4/dcf/classThread_1_1AddressResolver.html", "d4/dcf/classThread_1_1AddressResolver" ],
      [ "Buffer", "db/d50/classThread_1_1Buffer.html", "db/d50/classThread_1_1Buffer" ],
      [ "BufferHeader", "d2/d60/structThread_1_1BufferHeader.html", "d2/d60/structThread_1_1BufferHeader" ],
      [ "Child", "d3/de7/classThread_1_1Child.html", "d3/de7/classThread_1_1Child" ],
      [ "KeyManager", "d6/d44/classThread_1_1KeyManager.html", "d6/d44/classThread_1_1KeyManager" ],
      [ "LinkQualityInfo", "dd/d38/classThread_1_1LinkQualityInfo.html", "dd/d38/classThread_1_1LinkQualityInfo" ],
      [ "MeshForwarder", "dd/d1d/classThread_1_1MeshForwarder.html", "dd/d1d/classThread_1_1MeshForwarder" ],
      [ "Message", "dc/d3c/classThread_1_1Message.html", "dc/d3c/classThread_1_1Message" ],
      [ "MessageInfo", "de/dcc/structThread_1_1MessageInfo.html", "de/dcc/structThread_1_1MessageInfo" ],
      [ "MessageList", "da/d60/structThread_1_1MessageList.html", "da/d60/structThread_1_1MessageList" ],
      [ "MessageListEntry", "d9/dd7/structThread_1_1MessageListEntry.html", "d9/dd7/structThread_1_1MessageListEntry" ],
      [ "MessageQueue", "da/d1a/classThread_1_1MessageQueue.html", "da/d1a/classThread_1_1MessageQueue" ],
      [ "NcpBase", "d9/dc8/classThread_1_1NcpBase.html", "d9/dc8/classThread_1_1NcpBase" ],
      [ "NcpFrameBuffer", "d0/d78/classThread_1_1NcpFrameBuffer.html", "d0/d78/classThread_1_1NcpFrameBuffer" ],
      [ "NcpSpi", "d0/d2a/classThread_1_1NcpSpi.html", "d0/d2a/classThread_1_1NcpSpi" ],
      [ "NcpUart", "dc/d60/classThread_1_1NcpUart.html", "dc/d60/classThread_1_1NcpUart" ],
      [ "Neighbor", "da/dd9/classThread_1_1Neighbor.html", "da/dd9/classThread_1_1Neighbor" ],
      [ "Router", "db/d81/classThread_1_1Router.html", "db/d81/classThread_1_1Router" ],
      [ "Tasklet", "d4/d92/classThread_1_1Tasklet.html", "d4/d92/classThread_1_1Tasklet" ],
      [ "TaskletScheduler", "d8/de8/classThread_1_1TaskletScheduler.html", "d8/de8/classThread_1_1TaskletScheduler" ],
      [ "ThreadExtMacAddressTlv", "dc/d31/classThread_1_1ThreadExtMacAddressTlv.html", "dc/d31/classThread_1_1ThreadExtMacAddressTlv" ],
      [ "ThreadLastTransactionTimeTlv", "dc/dc8/classThread_1_1ThreadLastTransactionTimeTlv.html", "dc/dc8/classThread_1_1ThreadLastTransactionTimeTlv" ],
      [ "ThreadMeshLocalEidTlv", "df/d0c/classThread_1_1ThreadMeshLocalEidTlv.html", "df/d0c/classThread_1_1ThreadMeshLocalEidTlv" ],
      [ "ThreadMessageInfo", "df/d49/structThread_1_1ThreadMessageInfo.html", "df/d49/structThread_1_1ThreadMessageInfo" ],
      [ "ThreadNetif", "d3/d8e/classThread_1_1ThreadNetif.html", "d3/d8e/classThread_1_1ThreadNetif" ],
      [ "ThreadRloc16Tlv", "db/d2d/classThread_1_1ThreadRloc16Tlv.html", "db/d2d/classThread_1_1ThreadRloc16Tlv" ],
      [ "ThreadRouterMaskTlv", "dd/dd2/classThread_1_1ThreadRouterMaskTlv.html", "dd/dd2/classThread_1_1ThreadRouterMaskTlv" ],
      [ "ThreadStatusTlv", "d4/df4/classThread_1_1ThreadStatusTlv.html", "d4/df4/classThread_1_1ThreadStatusTlv" ],
      [ "ThreadTargetTlv", "df/d0b/classThread_1_1ThreadTargetTlv.html", "df/d0b/classThread_1_1ThreadTargetTlv" ],
      [ "ThreadTlv", "dd/d2b/classThread_1_1ThreadTlv.html", "dd/d2b/classThread_1_1ThreadTlv" ],
      [ "Timer", "d1/d40/classThread_1_1Timer.html", "d1/d40/classThread_1_1Timer" ],
      [ "TimerScheduler", "df/d1f/classThread_1_1TimerScheduler.html", "df/d1f/classThread_1_1TimerScheduler" ]
    ] ],
    [ "otActiveScanResult", "d1/de8/structotActiveScanResult.html", "d1/de8/structotActiveScanResult" ],
    [ "otBorderRouterConfig", "dd/dd0/structotBorderRouterConfig.html", "dd/dd0/structotBorderRouterConfig" ],
    [ "otChildInfo", "d3/d06/structotChildInfo.html", "d3/d06/structotChildInfo" ],
    [ "otEidCacheEntry", "d7/d52/structotEidCacheEntry.html", "d7/d52/structotEidCacheEntry" ],
    [ "otExtAddress", "d3/d8f/structotExtAddress.html", "d3/d8f/structotExtAddress" ],
    [ "otExternalRouteConfig", "d4/d5d/structotExternalRouteConfig.html", "d4/d5d/structotExternalRouteConfig" ],
    [ "otIp6Address", "d6/d55/structotIp6Address.html", "d6/d55/structotIp6Address" ],
    [ "otIp6Prefix", "d2/ddd/structotIp6Prefix.html", "d2/ddd/structotIp6Prefix" ],
    [ "otLeaderData", "d8/d4b/structotLeaderData.html", "d8/d4b/structotLeaderData" ],
    [ "otLinkModeConfig", "d6/df6/structotLinkModeConfig.html", "d6/df6/structotLinkModeConfig" ],
    [ "otMacCounters", "d4/d8c/structotMacCounters.html", "d4/d8c/structotMacCounters" ],
    [ "otMacWhitelistEntry", "d5/d3b/structotMacWhitelistEntry.html", "d5/d3b/structotMacWhitelistEntry" ],
    [ "otMessageInfo", "dd/d76/structotMessageInfo.html", "dd/d76/structotMessageInfo" ],
    [ "otNetifAddress", "d8/d1d/structotNetifAddress.html", "d8/d1d/structotNetifAddress" ],
    [ "otRouterInfo", "d9/d96/structotRouterInfo.html", "d9/d96/structotRouterInfo" ],
    [ "otSockAddr", "d3/d28/structotSockAddr.html", "d3/d28/structotSockAddr" ],
    [ "otUdpSocket", "da/dfd/structotUdpSocket.html", "da/dfd/structotUdpSocket" ],
    [ "RadioPacket", "db/ddc/structRadioPacket.html", "db/ddc/structRadioPacket" ],
    [ "spinel_eui48_t", "db/dd3/structspinel__eui48__t.html", "db/dd3/structspinel__eui48__t" ],
    [ "spinel_eui64_t", "df/d91/structspinel__eui64__t.html", "df/d91/structspinel__eui64__t" ],
    [ "spinel_ipv6addr_t", "dc/db6/structspinel__ipv6addr__t.html", "dc/db6/structspinel__ipv6addr__t" ],
    [ "spinel_net_xpanid_t", "d0/d83/structspinel__net__xpanid__t.html", "d0/d83/structspinel__net__xpanid__t" ],
    [ "va_list_obj", "dd/db1/structva__list__obj.html", "dd/db1/structva__list__obj" ]
];