#!/usr/bin/expect -f
#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

proc wait_for {command success {failure {[\r\n]FAILURE_NOT_EXPECTED[\r\n]}}} {
    set result 0
    set timeout 1
    for {set i 0} {$i < 20} {incr i} {
        if {$command != ""} {
            send "$command\n"
        }

        expect {
            -re $success {
                set result 1
            }
            -re $failure {
                exit 1
            }
            timeout {
                # Do nothing
            }
        }
        if {$result == 1} {
            break
        }
    }
    if {$result == 0} {
        exit 1
    }
}

proc spawn_node {id} {
    if {[info exists ::env(RCP_COMMAND)] && $::env(RCP_COMMAND) != ""} {
        spawn $::env(OT_COMMAND) "spinel+hdlc+uart://$::env(RCP_COMMAND)?forkpty-arg=$id"
    } else {
        spawn $::env(OT_COMMAND) $id
    }
    expect_after {
        timeout { exit 1 }
    }
    return $spawn_id
}

proc setup_leader {} {
    # Sets up a Thread network spawn_1 as the leader.
    global spawn_1
    global spawn_id
    global env

    set spawn_1 [spawn_node 1]

    set spawn_id $spawn_1
    send "dataset init new\n"
    expect "Done"
    send "dataset commit active\n"
    expect "Done"
    send "ifconfig up\n"
    expect "Done"
    send "thread start\n"
    expect "Done"
    wait_for "state" "leader"
    expect "Done"
}

proc dispose {} {
    send "\x04"
    expect eof
}

proc dispose_leader {} {
    global spawn_1
    global spawn_id

    set spawn_id $spawn_1
    dispose
}

set timeout 10
