#!/usr/bin/expect -f
#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

source "tests/scripts/expect/_common.exp"
source "tests/scripts/expect/_multinode.exp"

setup_nodes
set spawn_id $spawn_1

send "leaderdata\n"
expect -re {Partition ID: \d+}
expect -re {Weighting: \d+}
expect -re {Data Version: \d+}
expect -re {Stable Data Version: \d+}
expect -re {Leader Router ID: \d+}
expect "Done"

send "help\n"
expect "Done"

send "bufferinfo\n"
expect "Done"

send "ccathreshold -62\n"
expect "Done"
send "ccathreshold\n"
expect -- "-62 dBm"
expect "Done"

send "parent\n"
expect "Done"

send "delaytimermin 1\n"
expect "Done"
send "delaytimermin\n"
expect "1"
expect "Done"
send "delaytimermin 1 2\n"
send "counters mac 1\n"
expect "Error 7: InvalidArgs"

send "ifconfig down\n"
expect "Done"
send "ifconfig\n"
expect "down"
expect "Done"
send "ifconfig up\n"
expect "Done"
send "ifconfig\n"
expect "up"
expect "Done"

send "ipaddr add ::\n"
expect "Done"
send "ipaddr del ::\n"
expect "Done"

send "leaderweight 1\n"
expect "Done"
send "leaderweight\n"
expect "1"
expect "Done"

send "mode rsdn\n"
expect "Done"
send "mode\n"
expect -re "(?=.*r)(?=.*s)(?=.*d)(?=.*n)"

send "parent\n"
expect "Done"

send "singleton\n"
expect -re "true|false"
expect "Done"

send "state\n"
expect "disabled"
expect "Done"

send "txpower -10\n"
expect "Done"
send "txpower\n"
expect -- "-10 dBm"
expect "Done"

send "thread version\n"
expect "Done"

send "version\n"
expect "Done"
send "version api\n"
expect -re {\d+}
expect "Done"
send "version something_invalid\n"
expect "Error 35: InvalidCommand"

send "joinerport 10001\n"
expect "Done"
send "joinerport\n"
expect "10001"
expect "Done"

send "parentpriority 1\n"
expect "Done"
send "parentpriority\n"
expect "1"
expect "Done"

send "pollperiod 100000\n"
expect "Done"
send "pollperiod\n"
expect "100000"
expect "Done"

send "prefix add ::/64 low pdcrosn\n"
expect "Done"
send "prefix\n"
expect "0:0:0:0::/64 pdcrosn low"
expect "Done"

send "preferrouterid 1\n"
expect "Done"

send "route add ::/64 s low\n"
expect "Done"
send "route\n"
expect "0:0:0:0::/64 s low"
send "route remove ::/64\n"
expect "Done"

dispose_nodes
