#!/usr/bin/expect -f
#
#  Copyright (c) 2022, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

source "tests/scripts/expect/_common.exp"

spawn_node 1

send "diag start\n"
expect "start diagnostics mode"
expect "status 0x00"
expect_line "Done"

send "diag powersettings 11\n"
expect "failed"
expect "status 0x17"
expect_line "Error 23: NotFound"

send "diag powersettings\n"
expect "| StartCh | EndCh | TargetPower | ActualPower | RawPowerSetting |"
expect "+---------+-------+-------------+-------------+-----------------+"
expect_line "Done"

send "diag stop\n"
expect_line "Done"

send "region US\n"
expect_line "Done"

send "diag start\n"
expect "start diagnostics mode"
expect "status 0x00"
expect_line "Done"

send "diag powersettings 11\n"
expect -re {TargetPower\(0\.01dBm\): -?\d+}
expect -re {ActualPower\(0\.01dBm\): -?\d+}
expect -re {RawPowerSetting: [0-9]{1,16}}
expect_line "Done"

send "diag powersettings\n"
expect "| StartCh | EndCh | TargetPower | ActualPower | RawPowerSetting |"
expect "+---------+-------+-------------+-------------+-----------------+"
for {set i 1} {$i <= 4} {incr i} {
    expect -re "\\| +\\d+ | +\\d+ | +\\d+ | +\\d+ | +\[0-9\]\{1,16\} |"
}
expect_line "Done"

dispose_all
