#!/usr/bin/expect -f
#
#  Copyright (c) 2023, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

source "tests/scripts/expect/_common.exp"
source "tests/scripts/expect/_multinode.exp"

setup_two_nodes

switch_node 1
send "linkmetricsmgr enable\n"
expect_line "Done"
send "linkmetricsmgr\n"
expect_line "Enabled"
expect_line "Done"

sleep 10

switch_node 2
set addr [get_ipaddr mleid]

switch_node 1
send "ping $addr\n"
expect "16 bytes from $addr: icmp_seq=1"
send "linkmetricsmgr show\n"
expect -re {ExtAddr:([0-9a-f]){16}, LinkMargin:\d+, Rssi:\-?\d+}
expect "Done"

sleep 5

send "linkmetricsmgr disable\n"
expect_line "Done"
send "linkmetricsmgr\n"
expect_line "Disabled"
expect_line "Done"
send "linkmetricsmgr show\n"
expect_line "Done"
send "linkmetricsmgr xxx\n"
expect_line "InvalidCommand"

# Test continuous enable
send "linkmetricsmgr enable\n"
expect_line "Done"
send "linkmetricsmgr enable\n"
expect_line "Done"
send "linkmetricsmgr enable\n"
expect_line "Done"
send "linkmetricsmgr\n"
expect_line "Enabled"
expect_line "Done"

send "ping $addr\n"
expect "16 bytes from $addr: icmp_seq="

sleep 10

send "ping $addr\n"
expect "16 bytes from $addr: icmp_seq="

send "linkmetricsmgr show\n"
expect -re {ExtAddr:([0-9a-f]){16}, LinkMargin:\d+, Rssi:\-?\d+}
expect "Done"

# Test continuous disable
send "linkmetricsmgr disable\n"
expect_line "Done"
send "linkmetricsmgr disable\n"
expect_line "Done"
send "linkmetricsmgr disable\n"
expect_line "Done"
send "linkmetricsmgr\n"
expect_line "Disabled"
expect_line "Done"

send "ping $addr\n"
expect "16 bytes from $addr: icmp_seq="

sleep 10

send "ping $addr\n"
expect "16 bytes from $addr: icmp_seq="

send "linkmetricsmgr show\n"
expect_line "Done"

# Test continuous switch
send "linkmetricsmgr enable\n"
expect_line "Done"
send "linkmetricsmgr disable\n"
expect_line "Done"
send "linkmetricsmgr enable\n"
expect_line "Done"
send "linkmetricsmgr\n"
expect_line "Enabled"
expect_line "Done"

send "ping $addr\n"
expect "16 bytes from $addr: icmp_seq="

sleep 10

send "ping $addr\n"
expect "16 bytes from $addr: icmp_seq="

send "linkmetricsmgr show\n"
expect -re {ExtAddr:([0-9a-f]){16}, LinkMargin:\d+, Rssi:\-?\d+}
expect "Done"

send "linkmetricsmgr disable\n"
expect_line "Done"
send "linkmetricsmgr enable\n"
expect_line "Done"
send "linkmetricsmgr disable\n"
expect_line "Done"
send "linkmetricsmgr\n"
expect_line "Disabled"
expect_line "Done"

send "ping $addr\n"
expect "16 bytes from $addr: icmp_seq="

sleep 10

send "ping $addr\n"
expect "16 bytes from $addr: icmp_seq="

send "linkmetricsmgr show\n"
expect_line "Done"

dispose_all
