# File automatically generated by autoandr 0.00.01
# "examples/platforms/posix"
#

LOCAL_PATH := $(call my-dir)

#### BEGIN libopenthread-posix ####
include $(CLEAR_VARS)
LOCAL_MODULE := libopenthread-posix
LOCAL_CFLAGS += -D_GNU_SOURCE
LOCAL_CFLAGS += -DHAVE_CONFIG_H
LOCAL_CFLAGS += -DMBEDTLS_CONFIG_FILE=\"mbedtls-config.h\"
LOCAL_CFLAGS += -pedantic-errors
LOCAL_CFLAGS += -std=c99
LOCAL_CFLAGS += -Wall
LOCAL_CFLAGS += -Wextra
LOCAL_CFLAGS += -Wno-date-time
LOCAL_CFLAGS += -Wshadow
LOCAL_C_INCLUDES += $(LOCAL_PATH)/.
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../examples/platforms
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../examples/platforms/posix
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../examples/platforms/utils
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../src/core
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../third_party/mbedtls
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../third_party/mbedtls/repo/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../../third_party/mbedtls/repo/include/mbedtls
LOCAL_CPP_FEATURES +=
LOCAL_CPPFLAGS += -DHAVE_CONFIG_H
LOCAL_CPPFLAGS += -DMBEDTLS_CONFIG_FILE=\"mbedtls-config.h\"
LOCAL_CPPFLAGS += -std=gnu++98
LOCAL_CPPFLAGS += -Wall
LOCAL_CPPFLAGS += -Wextra
LOCAL_CPPFLAGS += -Wno-c++11-extensions
LOCAL_CPPFLAGS += -Wno-c++14-compat
LOCAL_CPPFLAGS += -Wno-date-time
LOCAL_CPPFLAGS += -Wno-gnu-anonymous-struct
LOCAL_CPPFLAGS += -Wno-nested-anon-types
LOCAL_CPPFLAGS += -Wno-non-virtual-dtor
LOCAL_CPPFLAGS += -Wno-pedantic
LOCAL_CPPFLAGS += -Wno-variadic-macros
LOCAL_CPPFLAGS += -Wno-zero-length-array
LOCAL_CPPFLAGS += -Wshadow
LOCAL_MODULE_TAGS += optional
LOCAL_SRC_FILES += ../../../../../examples/platforms/posix/alarm.c
LOCAL_SRC_FILES += ../../../../../examples/platforms/posix/flash.c
LOCAL_SRC_FILES += ../../../../../examples/platforms/posix/logging.c
LOCAL_SRC_FILES += ../../../../../examples/platforms/posix/misc.c
LOCAL_SRC_FILES += ../../../../../examples/platforms/posix/platform.c
LOCAL_SRC_FILES += ../../../../../examples/platforms/posix/radio.c
LOCAL_SRC_FILES += ../../../../../examples/platforms/posix/random.c
LOCAL_SRC_FILES += ../../../../../examples/platforms/posix/uart-posix.c
LOCAL_SRC_FILES += ../../../../../examples/platforms/utils/settings.cpp
include $(BUILD_STATIC_LIBRARY)
#### END libopenthread-posix ####
