[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "bbtc client"
version = "0.1.0"
description = "BBTC client for TCAT devices"
authors = ["Piotr Jasinski <piotr.jasinski@nordicsemi.no>"]

[tool.poetry.dependencies]
python = "^3.7"
bleak = "^0.20.2"
pytest ="^7.1.2"

[tool.poetry.dev-dependencies]
