# File automatically generated by autoandr 0.00.01
# "src/core"
#

LOCAL_PATH := $(call my-dir)

#### BEGIN libopenthread-ftd ####
include $(CLEAR_VARS)
LOCAL_MODULE := libopenthread-ftd
LOCAL_C_INCLUDES += $(LOCAL_PATH)/.
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../src/core
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party/mbedtls
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party/mbedtls/repo/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party/mbedtls/repo/include/mbedtls
LOCAL_CPP_FEATURES +=
LOCAL_CPPFLAGS += -DHAVE_CONFIG_H
LOCAL_CPPFLAGS += -DMBEDTLS_CONFIG_FILE=\"mbedtls-config.h\"
LOCAL_CPPFLAGS += -DOPENTHREAD_TARGET_LINUX
LOCAL_CPPFLAGS += -std=gnu++98
LOCAL_CPPFLAGS += -Wall
LOCAL_CPPFLAGS += -Wextra
LOCAL_CPPFLAGS += -Wno-c++11-extensions
LOCAL_CPPFLAGS += -Wno-c++14-compat
LOCAL_CPPFLAGS += -Wno-date-time
LOCAL_CPPFLAGS += -Wno-gnu-anonymous-struct
LOCAL_CPPFLAGS += -Wno-nested-anon-types
LOCAL_CPPFLAGS += -Wno-non-virtual-dtor
LOCAL_CPPFLAGS += -Wno-pedantic
LOCAL_CPPFLAGS += -Wno-variadic-macros
LOCAL_CPPFLAGS += -Wno-zero-length-array
LOCAL_CPPFLAGS += -Wshadow
LOCAL_MODULE_TAGS += optional
LOCAL_SRC_FILES += ../../../../src/core/api/link_raw_api.cpp
LOCAL_SRC_FILES += ../../../../src/core/coap/coap_base.cpp
LOCAL_SRC_FILES += ../../../../src/core/coap/coap_client.cpp
LOCAL_SRC_FILES += ../../../../src/core/coap/coap_header.cpp
LOCAL_SRC_FILES += ../../../../src/core/coap/coap_server.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/crc16.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/logging.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/message.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/tasklet.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/timer.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/tlvs.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/trickle_timer.cpp
LOCAL_SRC_FILES += ../../../../src/core/crypto/aes_ccm.cpp
LOCAL_SRC_FILES += ../../../../src/core/crypto/aes_ecb.cpp
LOCAL_SRC_FILES += ../../../../src/core/crypto/hmac_sha256.cpp
LOCAL_SRC_FILES += ../../../../src/core/crypto/mbedtls.cpp
LOCAL_SRC_FILES += ../../../../src/core/crypto/openthread-crypto.cpp
LOCAL_SRC_FILES += ../../../../src/core/crypto/sha256.cpp
LOCAL_SRC_FILES += ../../../../src/core/mac/mac_blacklist.cpp
LOCAL_SRC_FILES += ../../../../src/core/mac/mac.cpp
LOCAL_SRC_FILES += ../../../../src/core/mac/mac_frame.cpp
LOCAL_SRC_FILES += ../../../../src/core/mac/mac_whitelist.cpp
LOCAL_SRC_FILES += ../../../../src/core/meshcop/dataset.cpp
LOCAL_SRC_FILES += ../../../../src/core/meshcop/dataset_manager.cpp
LOCAL_SRC_FILES += ../../../../src/core/meshcop/dataset_manager_ftd.cpp
LOCAL_SRC_FILES += ../../../../src/core/meshcop/joiner_router.cpp
LOCAL_SRC_FILES += ../../../../src/core/meshcop/leader.cpp
LOCAL_SRC_FILES += ../../../../src/core/meshcop/timestamp.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/icmp6.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/ip6_address.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/ip6.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/ip6_filter.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/ip6_mpl.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/ip6_routes.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/netif.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/udp6.cpp
LOCAL_SRC_FILES += ../../../../src/core/openthread.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/address_resolver.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/announce_begin_server.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/energy_scan_server.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/key_manager.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/link_quality.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/lowpan.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/mesh_forwarder.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/mle.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/mle_router.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/network_data.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/network_data_leader.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/network_data_leader_ftd.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/network_data_local.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/network_diagnostic.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/panid_query_server.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/thread_netif.cpp
LOCAL_SRC_FILES += ../../../../src/core/utils/slaac_address.cpp
include $(BUILD_STATIC_LIBRARY)
#### END libopenthread-ftd ####

#### BEGIN libopenthread-mtd ####
include $(CLEAR_VARS)
LOCAL_MODULE := libopenthread-mtd
LOCAL_C_INCLUDES += $(LOCAL_PATH)/.
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../src/core
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party/mbedtls
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party/mbedtls/repo/include
LOCAL_C_INCLUDES += $(LOCAL_PATH)/../../../../third_party/mbedtls/repo/include/mbedtls
LOCAL_CPP_FEATURES +=
LOCAL_CPPFLAGS += -DHAVE_CONFIG_H
LOCAL_CPPFLAGS += -DMBEDTLS_CONFIG_FILE=\"mbedtls-config.h\"
LOCAL_CPPFLAGS += -DOPENTHREAD_MTD
LOCAL_CPPFLAGS += -DOPENTHREAD_TARGET_LINUX
LOCAL_CPPFLAGS += -std=gnu++98
LOCAL_CPPFLAGS += -Wall
LOCAL_CPPFLAGS += -Wextra
LOCAL_CPPFLAGS += -Wno-c++11-extensions
LOCAL_CPPFLAGS += -Wno-c++14-compat
LOCAL_CPPFLAGS += -Wno-date-time
LOCAL_CPPFLAGS += -Wno-gnu-anonymous-struct
LOCAL_CPPFLAGS += -Wno-nested-anon-types
LOCAL_CPPFLAGS += -Wno-non-virtual-dtor
LOCAL_CPPFLAGS += -Wno-pedantic
LOCAL_CPPFLAGS += -Wno-variadic-macros
LOCAL_CPPFLAGS += -Wno-zero-length-array
LOCAL_CPPFLAGS += -Wshadow
LOCAL_MODULE_TAGS += optional
LOCAL_SRC_FILES += ../../../../src/core/api/link_raw_api.cpp
LOCAL_SRC_FILES += ../../../../src/core/coap/coap_base.cpp
LOCAL_SRC_FILES += ../../../../src/core/coap/coap_client.cpp
LOCAL_SRC_FILES += ../../../../src/core/coap/coap_header.cpp
LOCAL_SRC_FILES += ../../../../src/core/coap/coap_server.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/crc16.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/logging.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/message.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/tasklet.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/timer.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/tlvs.cpp
LOCAL_SRC_FILES += ../../../../src/core/common/trickle_timer.cpp
LOCAL_SRC_FILES += ../../../../src/core/crypto/aes_ccm.cpp
LOCAL_SRC_FILES += ../../../../src/core/crypto/aes_ecb.cpp
LOCAL_SRC_FILES += ../../../../src/core/crypto/hmac_sha256.cpp
LOCAL_SRC_FILES += ../../../../src/core/crypto/mbedtls.cpp
LOCAL_SRC_FILES += ../../../../src/core/crypto/openthread-crypto.cpp
LOCAL_SRC_FILES += ../../../../src/core/crypto/sha256.cpp
LOCAL_SRC_FILES += ../../../../src/core/mac/mac_blacklist.cpp
LOCAL_SRC_FILES += ../../../../src/core/mac/mac.cpp
LOCAL_SRC_FILES += ../../../../src/core/mac/mac_frame.cpp
LOCAL_SRC_FILES += ../../../../src/core/mac/mac_whitelist.cpp
LOCAL_SRC_FILES += ../../../../src/core/meshcop/dataset.cpp
LOCAL_SRC_FILES += ../../../../src/core/meshcop/dataset_manager.cpp
LOCAL_SRC_FILES += ../../../../src/core/meshcop/timestamp.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/icmp6.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/ip6_address.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/ip6.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/ip6_filter.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/ip6_mpl.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/ip6_routes.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/netif.cpp
LOCAL_SRC_FILES += ../../../../src/core/net/udp6.cpp
LOCAL_SRC_FILES += ../../../../src/core/openthread.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/announce_begin_server.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/energy_scan_server.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/key_manager.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/link_quality.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/lowpan.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/mesh_forwarder.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/mle.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/network_data.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/network_data_leader.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/network_diagnostic.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/panid_query_server.cpp
LOCAL_SRC_FILES += ../../../../src/core/thread/thread_netif.cpp
LOCAL_SRC_FILES += ../../../../src/core/utils/slaac_address.cpp
include $(BUILD_STATIC_LIBRARY)
#### END libopenthread-mtd ####
