#!/bin/bash
#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -euxo pipefail

readonly OT_BUILDDIR="$(pwd)/build"

readonly OT_COMMON_OPTIONS=(
    "-DOT_COMPILE_WARNING_AS_ERROR=ON"
)

readonly OT_BASIC_CHECK_OPTIONS=(
    "-DOT_COMMISSIONER=ON"
    "-DOT_DHCP6_CLIENT=ON"
    "-DOT_DHCP6_SERVER=ON"
    "-DOT_DNS_CLIENT=ON"
    "-DOT_JOINER=ON"
)

reset_source()
{
    rm -rf "$OT_BUILDDIR"
}

build_cc1352()
{
    reset_source
    "$(dirname "$0")"/cmake-build cc1352 "${OT_COMMON_OPTIONS[@]}" "${OT_BASIC_CHECK_OPTIONS[@]}"
}

build_cc2538()
{
    reset_source
    "$(dirname "$0")"/cmake-build cc2538 "${OT_COMMON_OPTIONS[@]}" "${OT_BASIC_CHECK_OPTIONS[@]}"
}

build_cc2650()
{
    reset_source
    "$(dirname "$0")"/cmake-build cc2650 "${OT_COMMON_OPTIONS[@]}"
}

build_cc2652()
{
    reset_source
    "$(dirname "$0")"/cmake-build cc2652 "${OT_COMMON_OPTIONS[@]}" "${OT_BASIC_CHECK_OPTIONS[@]}"
}

build_kw41z()
{
    reset_source
    "$(dirname "$0")"/cmake-build kw41z "${OT_COMMON_OPTIONS[@]}" "${OT_BASIC_CHECK_OPTIONS[@]}"
}

build_nrf52811()
{
    reset_source
    "$(dirname "$0")"/cmake-build nrf52811 "$1" "${OT_COMMON_OPTIONS[@]}"
}

build_nrf52833()
{
    reset_source
    "$(dirname "$0")"/cmake-build nrf52833 "$1" "${OT_COMMON_OPTIONS[@]}" "${OT_BASIC_CHECK_OPTIONS[@]}"
}

build_nrf52840()
{
    reset_source
    "$(dirname "$0")"/cmake-build nrf52840 "$1" "${OT_COMMON_OPTIONS[@]}" "${OT_BASIC_CHECK_OPTIONS[@]}"
}

build_qpg6095()
{
    reset_source
    "$(dirname "$0")"/cmake-build qpg6095 "${OT_COMMON_OPTIONS[@]}" "${OT_BASIC_CHECK_OPTIONS[@]}"
}

build_samr21()
{
    reset_source

    asfzip=asf-standalone-archive-3.45.0.85.zip
    wget http://ww1.microchip.com/downloads/en/DeviceDoc/${asfzip}
    unzip -qq ${asfzip}
    mv xdk-asf-3.45.0 third_party/microchip/asf

    "$(dirname "$0")"/cmake-build samr21 "${OT_COMMON_OPTIONS[@]}" "${OT_BASIC_CHECK_OPTIONS[@]}"
}

main()
{
    export CPPFLAGS="${CPPFLAGS:-} -DNDEBUG"

    if [[ $# == 0 ]]; then
        build_cc1352
        build_cc2538
        build_cc2650
        build_cc2652
        build_kw41z
        build_qpg6095
        build_samr21
        # UART transport
        build_nrf52840 UART_trans
        # USB transport with bootloader e.g. to support PCA10059 dongle
        build_nrf52840 USB_trans_bl
        # SPI transport for NCP
        build_nrf52840 SPI_trans_NCP
        # Software cryptography
        build_nrf52840 soft_crypto
        # Software cryptography with threading support
        build_nrf52840 soft_crypto_threading
        return 0
    fi

    while [[ $# != 0 ]]; do
        "build_$1"
        shift
    done
}

main "$@"
