#!/bin/bash
#
#  Copyright (c) 2019, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#
#  Usage:
#  replace_macros.sh OPENTHREAD_CONFIG_HEADER_FILE

sed -i \
    -e 's/OPENTHREAD_CONFIG_ADDRESS_CACHE_ENTRIES\b/OPENTHREAD_CONFIG_TMF_ADDRESS_CACHE_ENTRIES/g'  \
    -e 's/OPENTHREAD_CONFIG_ADDRESS_QUERY_INITIAL_RETRY_DELAY\b/OPENTHREAD_CONFIG_TMF_ADDRESS_QUERY_INITIAL_RETRY_DELAY/g'  \
    -e 's/OPENTHREAD_CONFIG_ADDRESS_QUERY_MAX_RETRY_DELAY\b/OPENTHREAD_CONFIG_TMF_ADDRESS_QUERY_MAX_RETRY_DELAY/g'  \
    -e 's/OPENTHREAD_CONFIG_ADDRESS_QUERY_TIMEOUT\b/OPENTHREAD_CONFIG_TMF_ADDRESS_QUERY_TIMEOUT/g'  \
    -e 's/OPENTHREAD_CONFIG_ATTACH_BACKOFF_JITTER_INTERVAL\b/OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_JITTER_INTERVAL/g'  \
    -e 's/OPENTHREAD_CONFIG_ATTACH_BACKOFF_MAXIMUM_INTERVAL\b/OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_MAXIMUM_INTERVAL/g'  \
    -e 's/OPENTHREAD_CONFIG_ATTACH_BACKOFF_MINIMUM_INTERVAL\b/OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_MINIMUM_INTERVAL/g'  \
    -e 's/OPENTHREAD_CONFIG_ATTACH_DATA_POLL_PERIOD\b/OPENTHREAD_CONFIG_MAC_ATTACH_DATA_POLL_PERIOD/g'  \
    -e 's/OPENTHREAD_CONFIG_DEFAULT_CHILD_TIMEOUT\b/OPENTHREAD_CONFIG_MLE_CHILD_TIMEOUT_DEFAULT/g'  \
    -e 's/OPENTHREAD_CONFIG_DISABLE_CSMA_CA_ON_LAST_ATTEMPT\b/OPENTHREAD_CONFIG_MAC_DISABLE_CSMA_CA_ON_LAST_ATTEMPT/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_ANNOUNCE_SENDER\b/OPENTHREAD_CONFIG_ANNOUNCE_SENDER_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_ATTACH_BACKOFF\b/OPENTHREAD_CONFIG_MLE_ATTACH_BACKOFF_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_BEACON_RSP_WHEN_JOINABLE\b/OPENTHREAD_CONFIG_MAC_BEACON_RSP_WHEN_JOINABLE_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_DYNAMIC_MPL_INTERVAL\b/OPENTHREAD_CONFIG_MPL_DYNAMIC_INTERVAL_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_LONG_ROUTES\b/OPENTHREAD_CONFIG_MLE_LONG_ROUTES_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_PERIODIC_PARENT_SEARCH\b/OPENTHREAD_CONFIG_PARENT_SEARCH_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_PLATFORM_USEC_TIMER\b/OPENTHREAD_CONFIG_PLATFORM_USEC_TIMER_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_SLAAC\b/OPENTHREAD_CONFIG_IP6_SLAAC_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_SOFTWARE_ACK_TIMEOUT\b/OPENTHREAD_CONFIG_SOFTWARE_ACK_TIMEOUT_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_SOFTWARE_CSMA_BACKOFF\b/OPENTHREAD_CONFIG_SOFTWARE_CSMA_BACKOFF_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_SOFTWARE_ENERGY_SCAN\b/OPENTHREAD_CONFIG_SOFTWARE_ENERGY_SCAN_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_SOFTWARE_RETRANSMIT\b/OPENTHREAD_CONFIG_SOFTWARE_RETRANSMIT_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_STEERING_DATA_SET_OOB\b/OPENTHREAD_CONFIG_MLE_STEERING_DATA_SET_OOB_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_ENABLE_TIME_SYNC\b/OPENTHREAD_CONFIG_TIME_SYNC_ENABLE/g'  \
    -e 's/OPENTHREAD_CONFIG_HEADER_IE_SUPPORT\b/OPENTHREAD_CONFIG_MAC_HEADER_IE_SUPPORT/g'  \
    -e 's/OPENTHREAD_CONFIG_INFORM_PREVIOUS_PARENT_ON_REATTACH\b/OPENTHREAD_CONFIG_MLE_INFORM_PREVIOUS_PARENT_ON_REATTACH/g'  \
    -e 's/OPENTHREAD_CONFIG_IP_ADDRS_PER_CHILD\b/OPENTHREAD_CONFIG_MLE_IP_ADDRS_PER_CHILD/g'  \
    -e 's/OPENTHREAD_CONFIG_IP_ADDRS_TO_REGISTER\b/OPENTHREAD_CONFIG_MLE_IP_ADDRS_TO_REGISTER/g'  \
    -e 's/OPENTHREAD_CONFIG_IPV6_DEFAULT_HOP_LIMIT\b/OPENTHREAD_CONFIG_IP6_HOP_LIMIT_DEFAULT/g'  \
    -e 's/OPENTHREAD_CONFIG_IPV6_DEFAULT_MAX_DATAGRAM\b/OPENTHREAD_CONFIG_IP6_MAX_DATAGRAM_LENGTH/g'  \
    -e 's/OPENTHREAD_CONFIG_JOIN_BEACON_VERSION\b/OPENTHREAD_CONFIG_MAC_JOIN_BEACON_VERSION/g'  \
    -e 's/OPENTHREAD_CONFIG_MAX_CHILDREN\b/OPENTHREAD_CONFIG_MLE_MAX_CHILDREN/g'  \
    -e 's/OPENTHREAD_CONFIG_MAX_ENERGY_RESULTS\b/OPENTHREAD_CONFIG_TMF_ENERGY_SCAN_MAX_RESULTS/g'  \
    -e 's/OPENTHREAD_CONFIG_MAX_EXT_IP_ADDRS\b/OPENTHREAD_CONFIG_IP6_MAX_EXT_UCAST_ADDRS/g'  \
    -e 's/OPENTHREAD_CONFIG_MAX_EXT_MULTICAST_IP_ADDRS\b/OPENTHREAD_CONFIG_IP6_MAX_EXT_MCAST_ADDRS/g'  \
    -e 's/OPENTHREAD_CONFIG_MAX_JOINER_ENTRIES\b/OPENTHREAD_CONFIG_COMMISSIONER_MAX_JOINER_ENTRIES/g'  \
    -e 's/OPENTHREAD_CONFIG_MAX_JOINER_ROUTER_ENTRIES\b/OPENTHREAD_CONFIG_JOINER_MAX_CANDIDATES/g'  \
    -e 's/OPENTHREAD_CONFIG_MAX_ROUTERS\b/OPENTHREAD_CONFIG_MLE_MAX_ROUTERS/g'  \
    -e 's/OPENTHREAD_CONFIG_MAX_SERVICE_ALOCS\b/OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_MAX_ALOCS/g'  \
    -e 's/OPENTHREAD_CONFIG_MAX_TX_ATTEMPTS_INDIRECT_POLLS\b/OPENTHREAD_CONFIG_MAC_MAX_TX_ATTEMPTS_INDIRECT_POLLS/g'  \
    -e 's/OPENTHREAD_CONFIG_MESHCOP_PENDING_DATASET_DEFAULT_DELAY\b/OPENTHREAD_CONFIG_TMF_PENDING_DATASET_DEFAULT_DELAY/g'  \
    -e 's/OPENTHREAD_CONFIG_MESHCOP_PENDING_DATASET_MINIMUM_DELAY\b/OPENTHREAD_CONFIG_TMF_PENDING_DATASET_MINIMUM_DELAY/g'  \
    -e 's/OPENTHREAD_CONFIG_MINIMUM_POLL_PERIOD\b/OPENTHREAD_CONFIG_MAC_MINIMUM_POLL_PERIOD/g'  \
    -e 's/OPENTHREAD_CONFIG_NUM_DHCP_PREFIXES\b/OPENTHREAD_CONFIG_DHCP6_SERVER_NUM_PREFIXES/g'  \
    -e 's/OPENTHREAD_CONFIG_NUM_SLAAC_ADDRESSES\b/OPENTHREAD_CONFIG_IP6_SLAAC_NUM_ADDRESSES/g'  \
    -e 's/OPENTHREAD_CONFIG_RETX_POLL_PERIOD\b/OPENTHREAD_CONFIG_MAC_RETX_POLL_PERIOD/g'  \
    -e 's/OPENTHREAD_CONFIG_SEND_UNICAST_ANNOUNCE_RESPONSE\b/OPENTHREAD_CONFIG_MLE_SEND_UNICAST_ANNOUNCE_RESPONSE/g'  \
    -e 's/OPENTHREAD_CONFIG_SNTP_MAX_RETRANSMIT\b/OPENTHREAD_CONFIG_SNTP_CLIENT_MAX_RETRANSMIT/g'  \
    -e 's/OPENTHREAD_CONFIG_SNTP_RESPONSE_TIMEOUT\b/OPENTHREAD_CONFIG_SNTP_CLIENT_RESPONSE_TIMEOUT/g'  \
    -e 's/OPENTHREAD_CONFIG_STAY_AWAKE_BETWEEN_FRAGMENTS\b/OPENTHREAD_CONFIG_MAC_STAY_AWAKE_BETWEEN_FRAGMENTS/g'  \
    -e 's/OPENTHREAD_CONFIG_SUPERVISION_CHECK_TIMEOUT\b/OPENTHREAD_CONFIG_CHILD_SUPERVISION_CHECK_TIMEOUT/g'  \
    -e 's/OPENTHREAD_CONFIG_SUPERVISION_MSG_NO_ACK_REQUEST\b/OPENTHREAD_CONFIG_CHILD_SUPERVISION_MSG_NO_ACK_REQUEST/g'  \
    -e 's/OPENTHREAD_CONFIG_TX_NUM_BCAST\b/OPENTHREAD_CONFIG_MAC_TX_NUM_BCAST/g'  \
    -e 's/OPENTHREAD_ENABLE_APPLICATION_COAP\b/OPENTHREAD_CONFIG_COAP_API_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_APPLICATION_COAP_SECURE\b/OPENTHREAD_CONFIG_COAP_SECURE_API_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_BORDER_AGENT\b/OPENTHREAD_CONFIG_BORDER_AGENT_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_BORDER_ROUTER\b/OPENTHREAD_CONFIG_BORDER_ROUTER_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_CHANNEL_MANAGER\b/OPENTHREAD_CONFIG_CHANNEL_MANAGER_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_CHANNEL_MONITOR\b/OPENTHREAD_CONFIG_CHANNEL_MONITOR_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_CHILD_SUPERVISION\b/OPENTHREAD_CONFIG_CHILD_SUPERVISION_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_COMMISSIONER\b/OPENTHREAD_CONFIG_COMMISSIONER_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_DHCP6_CLIENT\b/OPENTHREAD_CONFIG_DHCP6_CLIENT_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_DHCP6_SERVER\b/OPENTHREAD_CONFIG_DHCP6_SERVER_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_DIAG\b/OPENTHREAD_CONFIG_DIAG_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_DNS_CLIENT\b/OPENTHREAD_CONFIG_DNS_CLIENT_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_DTLS\b/OPENTHREAD_CONFIG_DTLS_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_ECDSA\b/OPENTHREAD_CONFIG_ECDSA_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_JAM_DETECTION\b/OPENTHREAD_CONFIG_JAM_DETECTION_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_JOINER\b/OPENTHREAD_CONFIG_JOINER_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_LEGACY\b/OPENTHREAD_CONFIG_LEGACY_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_MAC_FILTER\b/OPENTHREAD_CONFIG_MAC_FILTER_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_MTD_NETWORK_DIAGNOSTIC\b/OPENTHREAD_CONFIG_TMF_NETWORK_DIAG_MTD_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_MULTIPLE_INSTANCES\b/OPENTHREAD_CONFIG_MULTIPLE_INSTANCE_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_NCP_SPI\b/OPENTHREAD_CONFIG_NCP_SPI_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_NCP_SPINEL_ENCRYPTER\b/OPENTHREAD_CONFIG_NCP_SPI_ENABLENEL_ENCRYPTER/g'  \
    -e 's/OPENTHREAD_ENABLE_NCP_UART\b/OPENTHREAD_CONFIG_NCP_UART_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_PLATFORM_NETIF\b/OPENTHREAD_CONFIG_PLATFORM_NETIF_ENABLE/g' \
    -e 's/OPENTHREAD_ENABLE_PLATFORM_UDP\b/OPENTHREAD_CONFIG_PLATFORM_UDP_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_RAW_LINK_API\b/OPENTHREAD_CONFIG_LINK_RAW_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_REFERENCE_DEVICE\b/OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_SERVICE\b/OPENTHREAD_CONFIG_TMF_NETDATA_SERVICE_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_SNTP_CLIENT\b/OPENTHREAD_CONFIG_SNTP_CLIENT_ENABLE/g'  \
    -e 's/OPENTHREAD_ENABLE_SPINEL_VENDOR_SUPPORT\b/OPENTHREAD_ENABLE_NCP_VENDOR_HOOK/g'  \
    -e 's/OPENTHREAD_ENABLE_UDP_FORWARD\b/OPENTHREAD_CONFIG_UDP_FORWARD_ENABLE/g' "${1}"

