#!/bin/bash
#
#  Copyright (c) 2026, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

set -euo pipefail

# Determine the temporary directory
TEMP_DIR="${TMPDIR:-/tmp}"

# Determine the repository root
REPO_ROOT="$(cd "$(dirname "$0")"/../.. && pwd)"

# Determine the build directory
if [[ -z ${top_builddir:-} ]]; then
    BUILD_DIR="build"
else
    BUILD_DIR="$top_builddir"
fi
if [[ $BUILD_DIR != /* ]]; then
    BUILD_DIR="${REPO_ROOT}/${BUILD_DIR}"
fi
NEXUS_BIN_DIR="${BUILD_DIR}/tests/nexus"

# Default test list if no arguments are provided
DEFAULT_TESTS=(
    "5_1_1"
    "5_1_2"
    "5_1_3"
    "5_1_4"
    "5_1_5"
    "5_1_6"
    "5_1_7"
    "5_1_8"
    "5_1_9"
    "5_1_10"
    "5_1_11"
    "5_1_12"
    "5_1_13"
    "5_2_1"
    "5_2_3"
    "5_2_4"
    "5_2_5"
    "5_2_6"
    "5_2_7"
    "5_3_1"
    "5_3_2"
    "5_3_3"
    "5_3_4"
    "5_3_5"
    "5_3_6"
    "5_3_7"
    "5_3_8"
    "5_3_9"
    "5_3_10"
    "5_3_11"
    "5_5_1"
    "5_5_2"
    "5_5_3"
    "5_5_4_1"
    "5_5_4_2"
    "5_5_5"
    "5_5_7"
    "5_6_1"
    "5_6_2"
    "5_7_1"
    "5_7_2"
    "5_7_3"
    "5_8_2"
    "5_8_3"
    "6_1_1_A"
    "6_1_1_B"
    "6_1_2_A"
    "6_1_2_B"
    "6_1_3_A"
    "6_1_3_B"
    "6_1_4"
    "6_1_5"
    "6_2_1_A"
    "6_2_1_B"
    "6_2_2"
    "6_3_1_A"
    "6_3_1_B"
    "6_3_2"
    "6_4_1_A"
    "6_4_1_B"
    "6_5_1"
    "7_1_1"
)

# Use provided arguments or the default test list
if [[ $# -eq 0 ]]; then
    TESTS_TO_RUN=("${DEFAULT_TESTS[@]}")
else
    TESTS_TO_RUN=("$@")
fi

failed_tests=()

run_test()
{
    local test_full="$1"
    # Strip 'nexus_' prefix if present
    test_full="${test_full#nexus_}"

    local test_base="${test_full%_[AB]}"
    local topology=""
    if [[ $test_full != "$test_base" ]]; then
        topology="${test_full##*_}"
    fi

    local test_name="nexus_${test_base}"
    local json_file="test_${test_full}.json"
    local pcap_file="test_${test_full}.pcap"
    local verify_script="${REPO_ROOT}/tests/nexus/verify_${test_base}.py"
    local nexus_bin="${NEXUS_BIN_DIR}/${test_name}"

    printf "========================================================================================\n"
    printf "Running %s...\n" "$test_full"
    printf "========================================================================================\n"

    if [[ ! -x $nexus_bin ]]; then
        printf "Error: %s not found or not executable in %s. Did you build the tests?\n" "$test_name" "$NEXUS_BIN_DIR" >&2
        return 1
    fi

    # Create a temporary directory for test artifacts
    local work_dir
    work_dir=$(mktemp -d "${TEMP_DIR}/nexus_test_${test_full}.XXXXXX")

    # Run the Nexus C++ test and verification in a subshell to isolate the working directory
    (
        cd "$work_dir"

        # 1. Run the Nexus C++ test
        export OT_NEXUS_PCAP_FILE="$pcap_file"
        if ! "$nexus_bin" "$topology" "$json_file"; then
            printf "C++ test %s FAILED\n" "$test_full" >&2
            exit 1
        fi

        # 2. Run the verification script if it exists
        if [[ -f $verify_script ]]; then
            printf "\n"
            printf "Running verification script %s...\n" "$verify_script"
            if [[ ! -f $json_file ]]; then
                printf "Error: %s not generated by %s.\n" "$json_file" "$test_name" >&2
                exit 1
            fi

            if ! python3 "$verify_script" "$json_file"; then
                printf "Verification for %s FAILED\n" "$test_full" >&2
                exit 1
            fi
        else
            printf "\n"
            printf "No verification script found for %s (%s), skipping verification.\n" "$test_full" "$verify_script"
        fi
    )

    local exit_code="$?"

    if [[ $exit_code -eq 0 ]]; then
        printf "\n"
        printf "%s PASSED\n" "$test_full"
        if [[ -d $work_dir && $work_dir == "${TEMP_DIR}/"* ]]; then
            rm -rf "$work_dir"
        fi
        return 0
    else
        printf "\n"
        printf "%s FAILED. Artifacts preserved in: %s\n" "$test_full" "$work_dir" >&2
        return 1
    fi
}

expanded_tests=()
for t in "${TESTS_TO_RUN[@]}"; do
    case "$t" in
        6_1_1 | 6_1_2 | 6_1_3 | 6_2_1 | 6_2_2 | 6_3_1 | 6_3_2 | 6_4_1 | 6_5_1)
            expanded_tests+=("${t}_A" "${t}_B")
            ;;
        *)
            expanded_tests+=("$t")
            ;;
    esac
done

for t in "${expanded_tests[@]}"; do
    if ! run_test "$t"; then
        failed_tests+=("$t")
    fi
done

printf "========================================================================================\n"
if [[ ${#failed_tests[@]} -eq 0 ]]; then
    printf "All tests passed successfully.\n"
    exit 0
else
    printf "The following tests FAILED:\n" >&2
    for f in "${failed_tests[@]}"; do
        printf "  - %s\n" "$f" >&2
    done
    exit 1
fi
