CC26xx Driver Library: cpu.c File Reference
cpu.c File Reference
#include <driverlib/cpu.h>
Functions
uint32_t CPUcpsid (void)
Disable all external interrupts.
uint32_t CPUprimask (void)
Get the current interrupt state.
uint32_t CPUcpsie (void)
Enable all external interrupts.
uint32_t CPUbasepriGet (void)
Get the interrupt priority disable level.
__asm (" .sect \".text:NOROM_CPUdelay\"\n"" .clink\n"" .thumbfunc NOROM_CPUdelay\n"" .thumb\n"" .global NOROM_CPUdelay\n""NOROM_CPUdelay:\n"" subs r0, #1\n"" bne.n NOROM_CPUdelay\n"" bx lr\n")
Provide a small delay.
Function Documentation
__asm (" .sect \".text:NOROM_CPUdelay\"\n"" .clink\n"" .thumbfunc NOROM_CPUdelay\n"" .thumb\n"" .global NOROM_CPUdelay\n""NOROM_CPUdelay:\n"" subs r0, #1\n""bne.n NOROM_CPUdelay\n""bx lr\n")
Provide a small delay.
Referenced by CPUbasepriGet(), CPUbasepriSet(), CPUcpsid(), CPUcpsie(), CPUprimask(), CPUsev(), CPUwfe(), and CPUwfi().