#
#  Copyright (c) 2020, The OpenThread Authors.
#  All rights reserved.
#
#  Redistribution and use in source and binary forms, with or without
#  modification, are permitted provided that the following conditions are met:
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in the
#     documentation and/or other materials provided with the distribution.
#  3. Neither the name of the copyright holder nor the
#     names of its contributors may be used to endorse or promote products
#     derived from this software without specific prior written permission.
#
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
#  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
#  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
#  ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
#  LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
#  CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
#  SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
#  INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
#  CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
#  ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
#  POSSIBILITY OF SUCH DAMAGE.
#

name: Simulation (expects)

on: [push, pull_request]

jobs:

  cancel-previous-runs:
    runs-on: ubuntu-latest
    steps:
    - uses: rokroskar/workflow-run-cleanup-action@master
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      if: "github.ref != 'refs/heads/master'"

  expects:
    runs-on: ubuntu-18.04
    env:
      CFLAGS: -DCLI_COAP_SECURE_USE_COAP_DEFAULT_HANDLER=1 -DOPENTHREAD_CONFIG_MLE_MAX_CHILDREN=15
      CXXFLAGS: -DCLI_COAP_SECURE_USE_COAP_DEFAULT_HANDLER=1 -DOPENTHREAD_CONFIG_MLE_MAX_CHILDREN=15
    steps:
    - uses: actions/checkout@v2
    - name: Bootstrap
      run: |
        OT_OPTIONS=-DOT_READLINE=OFF sudo apt-get --no-install-recommends install -y expect ninja-build
    - name: Run
      run: |
        OT_OPTIONS=-DOT_TIME_SYNC=ON VIRTUAL_TIME=0 ./script/test build expect
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
    - name: Run RCP Mode
      run: |
        OT_OPTIONS=-DOT_READLINE=OFF VIRTUAL_TIME=0 NODE_MODE=rcp ./script/test clean build expect
    - name: Keep POSIX Only
      run: |
        ./script/test tar simulation 1.1
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
    - name: Keep Simulation Only
      run: |
        ./script/test tar posix 1.1
        ./script/test untar simulation 1.1
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
    - name: Run TUN Mode
      run: |
        sudo apt-get install --no-install-recommends -y dnsmasq bind9-host ntp
        sudo systemctl start dnsmasq ntp
        host ipv6.google.com 127.0.0.1
        echo 'listen-address=::1' | sudo tee /etc/dnsmasq.conf
        echo 0 | sudo tee /proc/sys/net/ipv6/conf/all/disable_ipv6
        sudo systemctl restart dnsmasq
        host ipv6.google.com ::1
        OT_OPTIONS=-DOT_READLINE=OFF OT_NATIVE_IP=1 VIRTUAL_TIME=0 NODE_MODE=rcp ./script/test clean build expect
    - name: Keep POSIX Only
      run: |
        ./script/test tar simulation 1.1
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
    - name: Keep Simulation Only
      run: |
        ./script/test tar posix 1.1
        ./script/test untar simulation 1.1
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true

